AttendanceApp/AttendanceApp/Areas/Admin/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AttendanceApp.Models;
using AttendanceApp.ViewModel;
using System.IO;


namespace AttendanceApp.Areas.Admin.Controllers
{
    public class ApplicationUsersController : Controller
    {
        private AppDbContext db = new AppDbContext();

        public ActionResult Index()
        {
            var applicationUsers = db.Users.Include(a => a.position);
            return View(applicationUsers.ToList());
        }

        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        public ActionResult Create()
        {
            ViewBag.positionId = new SelectList(db.Positions, "Id", "positionName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ApplicationUsersViewModel viewModel)
        {

            if (viewModel.UploadedpicFile != null)
            {
                var extension = Path.GetExtension(path: viewModel.UploadedpicFile.FileName).ToLower();

                if (extension != ".jpg" && extension != ".png" && extension != ".gif" && extension != ".jpeg")
                {
                    ModelState.AddModelError("UploadedpicFile", "فایل ارسالی شما باید یک عکس باشد");
                }
            }

            if (ModelState.IsValid)
            {
                ApplicationUser applicationUser = new ApplicationUser();
                //intializing appuser variable
                applicationUser.PasswordHash = GetHashCode(viewModel.password);
                applicationUser.name = viewModel.name;
                applicationUser.birthDate = viewModel.birthDate;
                applicationUser.lastName = viewModel.lastName;
                applicationUser.Email = viewModel.Email;
                applicationUser.positionName = viewModel.positionName;
                applicationUser.address = viewModel.address;
                applicationUser.cellPhone = viewModel.cellPhone;
                applicationUser.gender = viewModel.gender;
                applicationUser.ManagerId = viewModel.ManagerId;
                //adding pic
                var extension = Path.GetExtension(viewModel.UploadedpicFile.FileName).ToLower();


                var fileName = $"{Guid.NewGuid()}{extension}";

                var path = Path.Combine(Server.MapPath("~/Images/"), fileName);

                viewModel.UploadedpicFile.SaveAs(path);
                applicationUser.picPath = fileName;

                db.Users.Add(applicationUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        private string GetHashCode(string password)
        {
         return GetHashCode(password);
        }

        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.positionId = new SelectList(db.Positions, "Id", "positionName", applicationUser.positionId);
            return View(applicationUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,name,lastName,positionName,address,cellPhone,birthDate,gender,picPath,ManagerId,positionId,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.positionId = new SelectList(db.Positions, "Id", "positionName", applicationUser.positionId);
            return View(applicationUser);
        }

        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AttendanceApp/AttendanceApp/Controllers/ManagerController.cs
using AttendanceApp.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AttendanceApp.Controllers
{
    public class ManagerController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Manager
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Commit(int? id)
        {
            inout a = db.Inouts.Find(id);
            a.isCommited = true;
            db.SaveChanges();
            return View();
        }
        [HttpPost]

        public ActionResult Isrest(int? id)
        {
            inout a = db.Inouts.Find(id);
                a.isRest = true;
            db.SaveChanges();

            return View();
        }
        public ActionResult RestIndex()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Acceptrest(int? id)
        {
            rest a = db.Rests.Find(id);
            a.isCommited = true;
            db.SaveChanges();

            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

AttendanceApp/AttendanceApp/Controllers/UserController.cs
using AttendanceApp.Models;
using AttendanceApp.ViewModel;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System;

namespace AttendanceApp.Controllers
{

    public class UserController : Controller
    {
       private AppDbContext db = new AppDbContext();

        // GET: User
        public ActionResult Index()
        { 
            var currentuserid= User.Identity.GetUserId();
          
            var userprofile = new UserProfileViewModel();
       
               
            userprofile.user = db.Users.Find(currentuserid);
            userprofile.rest = db.Rests.FirstOrDefault(x => x.personId == currentuserid);
            userprofile.IO = db.Inouts.FirstOrDefault(x => x.personId == currentuserid);


            return View(userprofile);
        }

        public ActionResult IOEntry()
        {
            var currentuserid = User.Identity.GetUserId();

            return View();
        }

        public ActionResult RestEntry()
        {
            var currentuserid = User.Identity.GetUserId();
            return View();
        }

        [HttpPost]
        public ActionResult RestEntry(rest rest)
        {
            var currentuserid = User.Identity.GetUserId();

            return View();
        }

        public ActionResult DailyReport()
        {
            var currentuserid = User.Identity.GetUserId();
            var dailyresult = db.Inouts.Where(n =>n.personId== currentuserid);
           
            return View(dailyresult.ToList());
        }
        [HttpPost]
        public ActionResult DailyReport(DateTime choosendate)
        {
            var currentuserid = User.Identity.GetUserId();
            var dailyresult = db.Inouts.Where(n => n.personId == currentuserid && n.date== choosendate);
          
            return View(dailyresult.ToList());
        }
        public ActionResult MonthlyReport(DateTime startdate, DateTime? enddate)
        {
            var currentuserid = User.Identity.GetUserId();
            if (enddate == null) { enddate = DateTime.Now; }
            var monthlyresult = db.Inouts.Where(n => n.personId == currentuserid &&
            (n.date >= startdate && n.date <= enddate));
            return View(monthlyresult.ToList());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AttendanceApp/AttendanceApp/Views/Shared/_Layout - manager.cshtml
@using AttendanceApp.Models
@using Microsoft.AspNet.Identity
@model LoginViewModel


<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - سیستم حضور و غیاب</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#"> سیستم حضور و غیاب</a>
                </div>
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "Manager")">
                            <span class="fa fa-home"></span>
                        </a>
                    </li>
                    <li><a href="@Url.Action("RestIndex", "Manager")">لیست درخواست های مرخصی</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </nav>
    </header>
    <div class="container" id="wrapper">
        <div class="row">
            <div class="col-md-12">
                @if (!string.IsNullOrEmpty(TempData["Message"]?.ToString()))
                {
                    <div class="alert alert-@(TempData["MessageClass"]??"success")">
                        @TempData["Message"]
                    </div>
                }

            </div>
        </div>
        <div class="row">
            <aside class="col-md-3">
                <div class="row">
                    <div class="col-md-12">
                        <a href="@Url.Action("Index","User")">ثبت ورود و خروج</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <section id="loginForm">
                            @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                            {
                                @Html.AntiForgeryToken()

                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <div class="checkbox " >
                                            @Html.CheckBoxFor(m => m.RememberMe)
                                            @Html.LabelFor(m => m.RememberMe)
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="ورود" class="btn btn-default" />
                                    </div>
                                </div>
                                @*<p>
                                        @Html.ActionLink("ثبت نام در سیستم ما", "Register")
                                    </p>*@
                                @* Enable this once you have account confirmation enabled for password reset functionality
                                    <p>
                                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                                    </p>*@
                            }
                        </section>
                    </div>
                    @* <div class="col-md-4">
                            <section id="socialLoginForm">
                                @Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
                            </section>
                        </div>*@
                </div>
              
            </aside>
            <main class="col-md-9">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <ul>
                        <li>
                            <a href="@Url.Action("Index", "ApplicationUsers", new { Area = "Admin" })">ورود به بخش مدیریت</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-6">

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center">
                &copy; @DateTime.Now.Year
                تمامی حقوق این سیستم متعلق به ..... است
            </div>
        </div>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AttendanceApp/AttendanceApp/Views/Shared/_Layout -UserProfile.cshtml
@using AttendanceApp.Models
@using Microsoft.AspNet.Identity



<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - سیستم حضور و غیاب</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#"> سیستم حضور و غیاب</a>
                </div>
                <ul class="nav navbar-nav">
                    <li>
                        @*@Html.ActionLink("خانه", "Index", "Home")*@
                        <a href="@Url.Action("Index", "Home")">
                            <span class="fa fa-home"></span>
                        </a>
                    </li>
                    <li class="active"><a href="#">لیست کارمندان</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            مدیر اداری
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">تنظیمات اولیه سیستم</a></li>
                            <li><a href="#">محاسبه کارکرد</a></li>

                        </ul>
                </ul>
                </li>


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </nav>
    </header>
    <div class="container" id="wrapper">
        <div class="row">
            <div class="col-md-12">
                @if (!string.IsNullOrEmpty(TempData["Message"]?.ToString()))
                {
                    <div class="alert alert-@(TempData["MessageClass"]??"success")">
                        @TempData["Message"]
                    </div>
                }

            </div>
        </div>
        <div class="row">
            <aside class="col-md-2">

                @Html.Partial("_UserProfilePartial")

            </aside>
            <main class="col-md-10">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <ul>
                        <li>
                            <a href="@Url.Action("Index", "ApplicationUsers", new { Area = "Admin" })">ورود به بخش مدیریت</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-6">

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center">
                &copy; @DateTime.Now.Year
                تمامی حقوق این سیستم متعلق به گروه دانیال است
            </div>
        </div>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <script>
        (function () {
            $(function () {

                $('#date-picker').MdPersianDateTimePicker({
                    Placement: 'bottom',
                    Trigger: 'click',
                    EnableTimePicker: false,
                    TargetSelector: '#date-picker',
                    GroupId: '',
                    ToDate: false,
                    FromDate: false,
                    DisableBeforeToday: true,
                    Disabled: false,
                    Format: 'yyyy/MM/dd',
                    IsGregorian: false,
                    EnglishNumber: true,
                    InLine: false
                });
            });
        })();
    </script>
</body>
</html>

AttendanceApp/AttendanceApp/Views/Shared/_Layout.cshtml
@using AttendanceApp.Models
@using Microsoft.AspNet.Identity
@model LoginViewModel


<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - سیستم حضور و غیاب</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#"> سیستم حضور و غیاب</a>
                </div>
                <ul class="nav navbar-nav">
                    <li>
                        @*@Html.ActionLink("خانه", "Index", "Home")*@
                        <a href="@Url.Action("Index", "Home")">
                            <span class="fa fa-home"></span>
                        </a>
                    </li>
                    <li class="active"><a href="#">لیست کارمندان</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            مدیر اداری
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">تنظیمات اولیه سیستم</a></li>
                            <li><a href="#">محاسبه کارکرد</a></li>

                        </ul>
                </ul>
                </li>


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </nav>
    </header>
    <div class="container" id="wrapper">
        <div class="row">
            <div class="col-md-12">
                @if (!string.IsNullOrEmpty(TempData["Message"]?.ToString()))
                {
                    <div class="alert alert-@(TempData["MessageClass"]??"success")">
                        @TempData["Message"]
                    </div>
                }

            </div>
        </div>
        <div class="row">
            <aside class="col-md-3">

                <div class="row">
                    <div class="col-md-12">
                        <section id="loginForm">
                            @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                            {
                                @Html.AntiForgeryToken()

                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <div class="checkbox " >
                                            @Html.CheckBoxFor(m => m.RememberMe)
                                            @Html.LabelFor(m => m.RememberMe)
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="ورود" class="btn btn-default" />
                                    </div>
                                </div>
                                @*<p>
                                        @Html.ActionLink("ثبت نام در سیستم ما", "Register")
                                    </p>*@
                                @* Enable this once you have account confirmation enabled for password reset functionality
                                    <p>
                                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                                    </p>*@
                            }
                        </section>
                    </div>
                    @* <div class="col-md-4">
                            <section id="socialLoginForm">
                                @Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
                            </section>
                        </div>*@
                </div>
              
            </aside>
            <main class="col-md-9">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <ul>
                        <li>
                            <a href="@Url.Action("Index", "ApplicationUsers", new { Area = "Admin" })">ورود به بخش مدیریت</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-6">

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center">
                &copy; @DateTime.Now.Year
                تمامی حقوق این سیستم متعلق به ..... است
            </div>
        </div>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AttendanceApp/AttendanceApp/Views/Shared/_UserProfilePartial.cshtml
@using AttendanceApp.Models
@using Microsoft.AspNet.Identity

<div class="row">

    <a href="@Url.Action("IOEntry")" class="btn btn-sm btn-link">
        <span class="fa fa-address-book"></span>
        ثبت ورود و خروج
    </a>
</div>
<div class="row">
    <a href="@Url.Action("RestEntry" )" class="btn btn-sm btn-link">
        <span class="fa fa-address-book"></span>
        ثبت مرخصی
    </a>
</div>
<div class="row">
    <a href="@Url.Action("DailyReport")" class="btn btn-sm btn-link">
        <span class="fa fa-address-book"></span>
        تایم شیت روزانه
    </a>
</div>
<div class="row">
    <a href="@Url.Action("MonthlyReport")" class="btn btn-sm btn-link">
        <span class="fa fa-address-book"></span>
        تایم شیت ماهانه
    </a>

</div>